version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"


  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      # Ignore JGit dependency(work not on jdk 8)
      - dependency-name: "org.eclipse.jgit:org.eclipse.jgit"
        version: "^5.13.0.202109080827-r"

      # Ignore Data faker dependency(work not on jdk 8)
      - dependency-name: "net.datafaker:datafaker"
        version: ["2.x"]